name: Install Geth
description: Installs Geth into your actions workflow
author: ApeWorX LTD <admin@apeworx.io>

branding:
  icon: 'download'
  color: 'blue'

inputs:
  version:
    description: |
      Geth version. Default will install whatever the latest release is from Github Releases.
    required: false
    default: latest

outputs:
  version:
    description: 'The actual version of Geth that was installed'
    value: ${{ steps.resolve-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Resolve Geth Version
      id: resolve-version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        INPUT_VERSION="${{ inputs.version }}"

        # Check if user wants latest version
        if [ "$INPUT_VERSION" = "latest" ]; then
          echo "Fetching latest Geth version..."

          # Get latest release from GitHub API
          # Use GITHUB_TOKEN to avoid rate limits
          LATEST_VERSION=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/ethereum/go-ethereum/releases/latest | grep '"tag_name":' | sed -E 's/.*"v?([^"]+)".*/\1/' || true)

          if [ -z "$LATEST_VERSION" ]; then
            echo "Error: Could not fetch latest version from GitHub API"
            exit 1
          fi

          GETH_VERSION="$LATEST_VERSION"
          echo "Latest version found: $GETH_VERSION"
        else
          # Normalize version format
          GETH_VERSION="$INPUT_VERSION"
        fi

        # Remove 'v' prefix if present (normalize to version number only)
        GETH_VERSION=${GETH_VERSION#v}

        # Validate version format (should be like x.x.x)
        if ! echo "$GETH_VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$'; then
          echo "Warning: Version '$GETH_VERSION' may not be in expected format (x.x.x)"
        fi

        echo "Resolved version: $GETH_VERSION"

        # Set output for use in other steps
        echo "version=$GETH_VERSION" >> $GITHUB_OUTPUT
        echo "version_with_v=v$GETH_VERSION" >> $GITHUB_OUTPUT

        # Also set environment variable for use in subsequent steps
        echo "GETH_VERSION=$GETH_VERSION" >> $GITHUB_ENV
        echo "GETH_VERSION_WITH_V=v$GETH_VERSION" >> $GITHUB_ENV

    - name: Install Geth on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "Installing Geth v${{ steps.resolve-version.outputs.version }} on Linux..."

        # Use the resolved version
        GETH_VERSION="${{ steps.resolve-version.outputs.version }}"
        GETH_VERSION_WITH_V="${{ steps.resolve-version.outputs.version_with_v }}"

        BASE_URL="https://gethstore.blob.core.windows.net/builds"

        echo "Attempting to download Geth ${GETH_VERSION} for Linux..."

        # Try multiple download strategies
        DOWNLOAD_SUCCESS=false

        # Strategy 1: Try GitHub releases API first (most reliable for tagged releases)
        echo "Trying GitHub releases..."
        RELEASE_URL=$(curl -s "https://api.github.com/repos/ethereum/go-ethereum/releases/tags/${GETH_VERSION_WITH_V}" 2>/dev/null | grep -o '"browser_download_url":"[^"]*linux-amd64[^"]*"' | cut -d'"' -f4 | head -1 || true)

        if [ -n "$RELEASE_URL" ]; then
          echo "Found release URL: $RELEASE_URL"
          if curl -L -f -o /tmp/geth.tar.gz "$RELEASE_URL" 2>/dev/null; then
            DOWNLOAD_SUCCESS=true
            echo "Downloaded from GitHub releases"
          fi
        fi

        # Strategy 2: Try blob storage with various patterns
        if [ "$DOWNLOAD_SUCCESS" = false ]; then
          echo "Trying blob storage..."

          # Get list of available files from blob storage
          BUILDS_LIST=$(curl -s "https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&prefix=geth-linux-amd64-${GETH_VERSION}" 2>/dev/null | grep -o 'geth-linux-amd64-[^<]*\.tar\.gz' | head -1 || true)

          if [ -n "$BUILDS_LIST" ]; then
            echo "Found build: $BUILDS_LIST"
            if curl -L -f -o /tmp/geth.tar.gz "${BASE_URL}/${BUILDS_LIST}" 2>/dev/null; then
              DOWNLOAD_SUCCESS=true
              echo "Downloaded from blob storage"
            fi
          fi
        fi

        # Strategy 3: Try direct patterns
        if [ "$DOWNLOAD_SUCCESS" = false ]; then
          echo "Trying direct URL patterns..."
          URLS=(
            "${BASE_URL}/geth-linux-amd64-${GETH_VERSION}.tar.gz"
            "https://github.com/ethereum/go-ethereum/releases/download/${GETH_VERSION_WITH_V}/geth-linux-amd64-${GETH_VERSION}.tar.gz"
          )

          for URL in "${URLS[@]}"; do
            echo "Trying: $URL"
            if curl -L -f -o /tmp/geth.tar.gz "$URL" 2>/dev/null; then
              DOWNLOAD_SUCCESS=true
              echo "Downloaded from: $URL"
              break
            fi
          done
        fi

        if [ "$DOWNLOAD_SUCCESS" = false ]; then
          echo "Error: Could not download Geth version ${GETH_VERSION} for Linux"
          echo "Please check if version ${GETH_VERSION} exists at https://github.com/ethereum/go-ethereum/releases"
          exit 1
        fi

        # Extract geth
        echo "Extracting Geth..."
        mkdir -p /tmp/geth-install
        tar -xzf /tmp/geth.tar.gz -C /tmp/geth-install

        # Find and move geth binary to /usr/local/bin
        GETH_DIR=$(find /tmp/geth-install -type d -name "geth-linux-amd64-*" | head -1)
        if [ -z "$GETH_DIR" ]; then
          echo "Error: Could not find extracted Geth directory"
          exit 1
        fi

        sudo mv "${GETH_DIR}/geth" /usr/local/bin/
        sudo chmod +x /usr/local/bin/geth

        # Cleanup
        rm -rf /tmp/geth.tar.gz /tmp/geth-install

        # Verify installation
        echo "Geth installed successfully!"
        geth version

        # Output installed version
        echo "::notice title=Geth Installed::Successfully installed Geth ${GETH_VERSION} on Linux"

    - name: Install Geth on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo "Installing Geth on macOS using Homebrew..."

        # Homebrew is the recommended way to install Geth on macOS
        # It handles code signing and dependencies correctly

        brew tap ethereum/ethereum
        brew install ethereum

        # Verify installation
        echo "Geth installed successfully!"
        INSTALLED_VERSION=$(geth version | grep "Version:" | awk '{print $2}' | cut -d- -f1)
        echo "Installed version: $INSTALLED_VERSION"

        REQUESTED_VERSION="${{ steps.resolve-version.outputs.version }}"

        if [ "$INSTALLED_VERSION" != "$REQUESTED_VERSION" ]; then
          echo "::warning::Installed version ($INSTALLED_VERSION) differs from requested version ($REQUESTED_VERSION). Homebrew always installs the latest version."
        fi

        echo "::notice title=Geth Installed::Successfully installed Geth $INSTALLED_VERSION on macOS"

    - name: Install Geth on Windows
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        Write-Host "Installing Geth v${{ steps.resolve-version.outputs.version }} on Windows..."

        # Use the resolved version
        $GethVersion = "${{ steps.resolve-version.outputs.version }}"
        $GethVersionWithV = "${{ steps.resolve-version.outputs.version_with_v }}"

        $BaseUrl = "https://gethstore.blob.core.windows.net/builds"

        Write-Host "Attempting to download Geth $GethVersion for Windows..."

        $TempFile = "$env:TEMP\geth.zip"
        $Downloaded = $false

        # Strategy 1: Try GitHub releases API first
        Write-Host "Trying GitHub releases..."
        try {
          $ReleaseInfo = Invoke-RestMethod -Uri "https://api.github.com/repos/ethereum/go-ethereum/releases/tags/$GethVersionWithV" -ErrorAction Stop
          $WindowsAsset = $ReleaseInfo.assets | Where-Object { $_.name -like "*windows-amd64*.zip" } | Select-Object -First 1

          if ($WindowsAsset) {
            Write-Host "Found release URL: $($WindowsAsset.browser_download_url)"
            Invoke-WebRequest -Uri $WindowsAsset.browser_download_url -OutFile $TempFile -ErrorAction Stop
            $Downloaded = $true
            Write-Host "Downloaded from GitHub releases"
          }
        } catch {
          Write-Host "GitHub releases attempt failed: $_"
        }

        # Strategy 2: Try blob storage
        if (-not $Downloaded) {
          Write-Host "Trying blob storage..."
          try {
            # Get list of available files
            $BuildsUrl = "https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&prefix=geth-windows-amd64-$GethVersion"
            $Response = Invoke-WebRequest -Uri $BuildsUrl -ErrorAction Stop

            if ($Response.Content -match 'geth-windows-amd64-[^<]+\.zip') {
              $FileName = $Matches[0]
              Write-Host "Found build: $FileName"
              $DownloadUrl = "$BaseUrl/$FileName"
              Invoke-WebRequest -Uri $DownloadUrl -OutFile $TempFile -ErrorAction Stop
              $Downloaded = $true
              Write-Host "Downloaded from blob storage"
            }
          } catch {
            Write-Host "Blob storage attempt failed: $_"
          }
        }

        # Strategy 3: Try direct URL patterns
        if (-not $Downloaded) {
          Write-Host "Trying direct URL patterns..."
          $Urls = @(
            "$BaseUrl/geth-windows-amd64-$GethVersion.zip",
            "https://github.com/ethereum/go-ethereum/releases/download/$GethVersionWithV/geth-windows-amd64-$GethVersion.zip"
          )

          foreach ($Url in $Urls) {
            try {
              Write-Host "Trying: $Url"
              Invoke-WebRequest -Uri $Url -OutFile $TempFile -ErrorAction Stop
              $Downloaded = $true
              Write-Host "Downloaded from: $Url"
              break
            } catch {
              continue
            }
          }
        }

        if (-not $Downloaded) {
          Write-Error "Could not download Geth version $GethVersion for Windows"
          Write-Error "Please check if version $GethVersion exists at https://github.com/ethereum/go-ethereum/releases"
          exit 1
        }

        # Extract geth
        Write-Host "Extracting Geth..."
        Expand-Archive -Path $TempFile -DestinationPath $env:TEMP -Force

        # Find geth.exe
        $GethExe = Get-ChildItem -Path $env:TEMP -Filter "geth.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1

        if (-not $GethExe) {
          Write-Error "Could not find geth.exe in extracted files"
          exit 1
        }

        # Create directory and move geth.exe
        $InstallPath = "C:\tools\geth"
        New-Item -ItemType Directory -Path $InstallPath -Force | Out-Null

        Move-Item -Path $GethExe.FullName -Destination "$InstallPath\geth.exe" -Force

        # Add to PATH for current session
        $env:PATH = "$InstallPath;$env:PATH"

        # Add to GitHub Actions PATH
        echo "$InstallPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        # Cleanup
        Remove-Item -Path $TempFile -Force -ErrorAction SilentlyContinue

        # Verify installation
        Write-Host "Geth installed successfully!"
        & "$InstallPath\geth.exe" version

        # Output installed version
        Write-Host "::notice title=Geth Installed::Successfully installed Geth $GethVersion on Windows"
